## Задача №3

В данном задании вам необходимо реализовать функции ошибки для линейной регрессии и их производные по параметрам, __не используя автоматические дифференцирование.__ Все методы должны быть реализованы только с использованием библиотеки `numpy`. 

Ваша основная задача: вывести формулы для производных __MSE, MAE, L1 и L2 регуляризационных членов__ в _векторном случае_ (т.е. когда и объект $\mathbf{x}_i$, и целевое значение $\mathbf{y}_i$ являются векторами.


Для работы обратимся к [Boston housing prices dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_boston.html). Он был предобработан для вашего удобства и будет загружен ниже.

In [1]:
"""
If you are using Google Colab, uncomment the next line to download `boston_subset.json`
"""
# !wget https://raw.githubusercontent.com/girafe-ai/ml-course/23f_yandex_ml_trainings/homeworks/assignment03_derivatives/boston_subset.json

'\nIf you are using Google Colab, uncomment the next line to download `boston_subset.json`\n'

In [2]:
# Run some setup code for this notebook.
import random
import numpy as np
import matplotlib.pyplot as plt

In [3]:
import json

with open("boston_subset.json", "r") as iofile:
    dataset = json.load(iofile)
feature_matrix = np.array(dataset["data"])
targets = np.array(dataset["target"])

## Имплементация функций потерь и методов регуляризации.
Для того, чтобы решить задание, вам необходимо реализовать все методы в файле `loss_and_derivatives.py`. Для вашего удобства код скопирован внутрь ноутбука в следующую ячейку. После решения ноутбука можете просто перенести его в .py файл.
__Внимание, в данном задании не требуется использовать свободный член (bias term)__, т.е. линейная модель примет простой вид
$$
\hat{\mathbf{y}} = XW
$$
Единичный столбец также не добавляется к матрице $X$.

Реализуйте методы для MSE, MAE, L1 и L2 регуляризации, а также вычисления их производных (опциональное задание) по параметрам линейной модели.

__Для вашего удобства данные уже предобработаны, и использование линейной модели без свободного члена не является ошибкой. В данном задании он не должен быть использован.__

In [4]:
try:
    del LossAndDerivatives
except:
    pass

from derivatives import LossAndDerivatives

Обращаем ваше внимание, требуется реализовать решение в векторном виде (т.е. для каждого объекта предсказание $\hat{\mathbf{y}}$ является вектором с размерностью $\geq 1$.

__Внимание! При подсчете ошибки она усредняется как по объектам, так и по размерности y. Аналогичное верно и для производных__.

Например, для вектора отклонений на одном объекте $[1., 1., 1., 1.]$ значение функции ошибки будет равно $\frac{1}{4}(1. + 1. + 1. + 1.)$ 

Для вашего удобства метод `.mse` уже реализован и вы можете обращаться к нему за примером.

Для проверки своего кода вам доступно несколько assert'ов:

In [5]:
w = np.array([1.0, 1.0])
x_n, y_n = feature_matrix, targets

# Repeating data to make everything multi-dimentional
w = np.vstack(
    [w[None, :] + 0.27, w[None, :] + 0.22, w[None, :] + 0.45, w[None, :] + 0.1]
).T
y_n = np.hstack([y_n[:, None], 2 * y_n[:, None], 3 * y_n[:, None], 4 * y_n[:, None]])

In [6]:
w[0, :].shape

(4,)

In [7]:
LossAndDerivatives.mse_derivative(x_n, y_n, w)

array([[ 7.32890068, 12.88731311, 18.82128365, 23.97731238],
       [ 9.55674399, 17.05397661, 24.98807528, 32.01723714]])

In [8]:
reference_mse_derivative = np.array(
    [
        [7.32890068, 12.88731311, 18.82128365, 23.97731238],
        [9.55674399, 17.05397661, 24.98807528, 32.01723714],
    ]
)
reference_l2_reg_derivative = np.array([[2.54, 2.44, 2.9, 2.2], [2.54, 2.44, 2.9, 2.2]])

assert np.allclose(
    reference_mse_derivative, LossAndDerivatives.mse_derivative(x_n, y_n, w), rtol=1e-3
), "Something wrong with MSE derivative"

assert np.allclose(
    reference_l2_reg_derivative, LossAndDerivatives.l2_reg_derivative(w), rtol=1e-3
), "Something wrong with L2 reg derivative"

print(
    "MSE derivative:\n{} \n\nL2 reg derivative:\n{}".format(
        LossAndDerivatives.mse_derivative(x_n, y_n, w),
        LossAndDerivatives.l2_reg_derivative(w),
    )
)

MSE derivative:
[[ 7.32890068 12.88731311 18.82128365 23.97731238]
 [ 9.55674399 17.05397661 24.98807528 32.01723714]] 

L2 reg derivative:
[[2.54 2.44 2.9  2.2 ]
 [2.54 2.44 2.9  2.2 ]]


In [9]:
reference_mae_derivative = np.array(
    [
        [0.19708867, 0.19621798, 0.19621798, 0.19572906],
        [0.25574138, 0.25524507, 0.25524507, 0.25406404],
    ]
)
reference_l1_reg_derivative = np.array([[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]])

assert np.allclose(
    reference_mae_derivative, LossAndDerivatives.mae_derivative(x_n, y_n, w), rtol=1e-3
), "Something wrong with MAE derivative"

assert np.allclose(
    reference_l1_reg_derivative, LossAndDerivatives.l1_reg_derivative(w), rtol=1e-3
), "Something wrong with L1 reg derivative"

print(
    "MAE derivative:\n{} \n\nL1 reg derivative:\n{}".format(
        LossAndDerivatives.mae_derivative(x_n, y_n, w),
        LossAndDerivatives.l1_reg_derivative(w),
    )
)

MAE derivative:
[[0.19708867 0.19621798 0.19621798 0.19572906]
 [0.25574138 0.25524507 0.25524507 0.25406404]] 

L1 reg derivative:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Градиентный спуск для решения реальной задачи
Следующая функция позволяет найти оптимальные значения параметров с помощью градиентного спуска:

In [10]:
def get_w_by_grad(
    X, Y, w_0, loss_mode="mse", reg_mode=None, lr=0.05, n_steps=100, reg_coeff=0.05
):
    if loss_mode == "mse":
        loss_function = LossAndDerivatives.mse
        loss_derivative = LossAndDerivatives.mse_derivative
    elif loss_mode == "mae":
        loss_function = LossAndDerivatives.mae
        loss_derivative = LossAndDerivatives.mae_derivative
    else:
        raise ValueError(
            "Unknown loss function. Available loss functions: `mse`, `mae`"
        )

    if reg_mode is None:
        reg_function = LossAndDerivatives.no_reg
        reg_derivative = (
            LossAndDerivatives.no_reg_derivative
        )  # lambda w: np.zeros_like(w)
    elif reg_mode == "l2":
        reg_function = LossAndDerivatives.l2_reg
        reg_derivative = LossAndDerivatives.l2_reg_derivative
    elif reg_mode == "l1":
        reg_function = LossAndDerivatives.l1_reg
        reg_derivative = LossAndDerivatives.l1_reg_derivative
    else:
        raise ValueError(
            "Unknown regularization mode. Available modes: `l1`, `l2`, None"
        )

    w = w_0.copy()

    for i in range(n_steps):
        empirical_risk = loss_function(X, Y, w) + reg_coeff * reg_function(w)
        gradient = loss_derivative(X, Y, w) + reg_coeff * reg_derivative(w)
        gradient_norm = np.linalg.norm(gradient)
        if gradient_norm > 5.0:
            gradient = gradient / gradient_norm * 5.0
        w -= lr * gradient

        if i % 25 == 0:
            print(
                "Step={}, loss={},\ngradient values={}\n".format(
                    i, empirical_risk, gradient
                )
            )
    return w

Рассмотрим простой пример:

In [11]:
# Initial weight matrix
w = np.ones((2, 1), dtype=float)
y_n = targets[:, None]

In [12]:
w_grad = get_w_by_grad(x_n, y_n, w, loss_mode="mse", reg_mode="l2", n_steps=250)

Step=0, loss=231.28353984777308,
gradient values=[[3.03360308]
 [3.97457575]]

Step=25, loss=58.512903511682715,
gradient values=[[2.28551977]
 [4.44706638]]

Step=50, loss=48.29584498872882,
gradient values=[[-0.89558132]
 [ 0.76425616]]

Step=75, loss=47.292783042717005,
gradient values=[[-0.48111511]
 [ 0.40907079]]

Step=100, loss=47.00419092029711,
gradient values=[[-0.25806412]
 [ 0.21942022]]

Step=125, loss=46.921159712801064,
gradient values=[[-0.1384223 ]
 [ 0.11769421]]

Step=150, loss=46.897270698227686,
gradient values=[[-0.07424796]
 [ 0.06312967]]

Step=175, loss=46.890397559386315,
gradient values=[[-0.03982566]
 [ 0.03386195]]

Step=200, loss=46.88842007984702,
gradient values=[[-0.02136197]
 [ 0.01816312]]

Step=225, loss=46.88785113668749,
gradient values=[[-0.01145829]
 [ 0.00974247]]



### Сравнение с `sklearn`
Сравним реализованную модель с версией из `sklearn`:

In [13]:
from sklearn.linear_model import Ridge

In [14]:
lr = Ridge(alpha=0.05)
lr.fit(x_n, y_n)
print(
    "sklearn linear regression implementation delivers MSE = {}".format(
        np.mean((lr.predict(x_n) - y_n) ** 2)
    )
)

sklearn linear regression implementation delivers MSE = 130.7141945947525


In [15]:
plt.scatter(x_n[:, -1], y_n[:, -1])
plt.scatter(
    x_n[:, -1],
    x_n.dot(w_grad)[:, -1],
    color="orange",
    label="Handwritten linear regression",
    linewidth=5,
)
plt.scatter(x_n[:, -1], lr.predict(x_n), color="cyan", label="sklearn Ridge")
plt.legend()
plt.show()

Если в полученных решениях есть небольшие различия, это не страшно. Модель основанная на вашей реализации не использует свободный член (он равен $0$), в то время версия из `sklearn` настраивает и его.

### Сдача решения
Сдайте в чекер реализованный класс `LossAndDerivatives`. Для этого можете скопировать всю ячейку с кодом (в том числе и импортирование `numpy`) в файл `derivatives.py`.

На этом задача завершена. Поздравляем!